### ISSUE TITLE
Issues with namespaces and template arguments.

### ISSUE THREAD

**Issue by SGSSGene** [boost-ext/reflect#12] opened 2024-02-23 13:36 UTC
If the argument of a template argument is inside an namespace, the `type_name()` functionality doesn't return a useful name:

```
template <typename T> struct A {};
namespace n {
  struct B {};
}

static_assert("B>"sv == reflect::type_name<A<n::B>>()); // unexpectedly passes
```
or see:

https://godbolt.org/z/3bTErb9j5

**Comment by krzysztof-jusiak** [comment] 2024-02-23 15:13
So I pushed the fix for type_name - https://github.com/boost-ext/reflect/commit/57af5090a0b4edda0649009bffbb545cdac76d4f. That will now returns `A` for the case above as the type name by default is the unqualified type_name. I'm planning to add qualified_type_name as a follow-up which will also return fully qualified namespaces.

**Comment by krzysztof-jusiak** [comment] 2024-02-23 15:50
Closing as the issue is fixed and a new feature will be added as a follow-up.

**Closed by krzysztof-jusiak** 2024-02-23 15:50 UTC
